### ISSUE TITLE
clr-init pulls /usr/lib64/haswell versions of libraries, won't work on non-AVX2 systems.

### ISSUE THREAD

**Issue by ahkok** [clearlinux/clr-init#1]
The initrd `Makefile` code relies on `ldd` which will provide the AVX2 optimized libraries as link targets if it runs on a machine that has AVX2.

This makes the initrd nonfunctional on all non-AVX2 systems, such as IVB.

The code can not rely on `ldd` plain output for finding required libraries. It should remain functional on older platforms.

```
$ python3 /usr/share/clr-avx-tools/avxjudge.py libcryptsetup.so.12
Analyzing libcryptsetup.so.12
Top SSE functions by instruction count
    crypt_benchmark_pbkdf@@CRYPTSETUP_2.0	17.14 %s
    crypt_benchmark@@CRYPTSETUP_2.0	5.88 %s
    crypt_convert@@CRYPTSETUP_2.0 	3.36 %s
    crypt_get_integrity_info@@CRYPTSETUP_2.0	2.9 %s
    .fini                         	2.84 %s

Top SSE functions by value
    .fini                         	116.76
    crypt_token_register@@CRYPTSETUP_2.0	103.78
    crypt_set_debug_level@@CRYPTSETUP_2.0	25.02
    crypt_wipe@@CRYPTSETUP_2.0    	22.17
    crypt_set_pbkdf_type@@CRYPTSETUP_2.0	9.05

Top AVX2 functions by instruction count
    .fini                         	1.7 %s
    crypt_benchmark@@CRYPTSETUP_2.0	0.74 %s
    crypt_token_register@@CRYPTSETUP_2.0	0.46 %s
    crypt_init_by_name_and_header@@CRYPTSETUP_2.0	0.13 %s
    crypt_set_pbkdf_type@@CRYPTSETUP_2.0	0.03 %s

Top AVX2 functions by value
    .fini                         	16.23
    crypt_token_register@@CRYPTSETUP_2.0	12.88
    crypt_benchmark@@CRYPTSETUP_2.0	2.0
    crypt_init_by_name_and_header@@CRYPTSETUP_2.0	0.2
    crypt_set_pbkdf_type@@CRYPTSETUP_2.0	0.1

Top AVX512 functions by instruction count

Top AVX512 functions by value


File total (SSE):  652 instructions with score 313
File total (AVX2):  342 instructions with score 31
File total (AVX512):  0 instructions with score 0

```

**Comment by ahkok** [comment]
@mdhorn

**Comment by ahkok** [comment]
```
--- Makefile~	2018-11-28 14:11:27.344436518 -0800
+++ Makefile	2018-11-28 14:11:41.471436383 -0800
@@ -6,7 +6,7 @@
     do \
         cp -f $$file initramfs/$$file;\
     done && \
-    cp $$(ldd $(BINFILES) | awk '{print $$3}' | grep "^/" | sort | uniq) initramfs/usr/lib64/ && \
+    cp $$(ldd $(BINFILES) | sed 's/haswell\///' | awk '{print $$3}' | grep "^/" | sort | uniq) initramfs/usr/lib64/ && \
     cd initramfs && \
```

**Comment by ahkok** [comment]
I'm not sure this is the right solution. We probably do not want to balloon the size of the initrd and just use one copy of the binaries/libraries. Duplicating libs will cost extra time and space.

**Comment by fenrus75** [comment]
we also need to look at how much of what ends up in an initrd we
could/should static link

**Comment by mdhorn** [comment]
On the plus side, I was able to verify that the current solution implemented, though maybe too big in size, does solve the issue we were seeing on older hardware (Ivy bridge).

**Comment by josuedhg** [comment]
@fenrus75 do u mean make a custom init program instead use systemd? I can continue with this old work https://github.com/clearlinux/clr-init/tree/e5490d381f893ae6212f98916a4b4e317c1b4013 obviously linking static and added stuffs like kernel events that systemd supports

**Comment by ahkok** [comment]
> do u mean make a custom init program

yes. Instead of relying on ~40mb of linux binaries, can we instead do what is needed in a few MB's ? Kind of like init-rdahead?

**Comment by mdhorn** [comment]
@josuedhg  When I built the change you had in clr-init, I was able to boot my older ivy bridge system.
But when I try using 26600 which has the new release of clr-init, it fails to boot with a different error than the previous invalid opcode. Now I see:
```
[    0.632648] intel_powerclamp: CPU does not support MWAIT
/init: error while loading shared libraries: libcryptsetup.so.12: cannot open shared object file: No such file or directory
[    0.802181] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    0.802181]
```
So we do not have a working solution for pre-Haswell hardware in the current release.

**Comment by mdhorn** [comment]
@josuedhg I was able to verify version V1.0.3 in Clear Linux OS release 26670 works on both Ivy Bridge laptops I have; one tested with a VM and the other with bare metal.

**Comment by josuedhg** [comment]
@ahkok we can, probably not as simple as init-rdahead but a custom init will be smaller

**Comment by josuedhg** [comment]
@mdhorn @ahkok @fenrus75 I will close this issue and a new one will be opened with the Idea of an smaller initrd
